{% set name = "questionary" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/questionary-{{ version }}.tar.gz
  sha256: bcce898bf3dbb446ff62830c86c5c6fb9a22a54146f0f5597d3da43b10d8fc8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python >=3.8
    - poetry-core
    - pip
  run:
    - python >=3.8
    - prompt_toolkit >=2.0,<=3.0.36

test:
  imports:
    - questionary
    - questionary.prompts
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/tmbo/questionary
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python library to build pretty command line prompts.
  description: Easy to use multi-select lists, confirmations, free text prompts...
  doc_url: https://github.com/tmbo/questionary#documentation
  dev_url: https://github.com/tmbo/questionary

extra:
  recipe-maintainers:
    - apeltzer
    - ewels
